### ISSUE TITLE
Need php-openid. May be 

### ISSUE THREAD

**Issue by belonesox** [mediawiki4intranet/OpenID#1]
Actually «The extension depends on the PHP library for OpenID https://github.com/openid/php-openid» http://www.mediawiki.org/wiki/Extension:OpenID

without it «require_once(Auth/OpenID/Consumer.php): failed»

But I dont know is it possible to implement hacky deploy

---

git clone git://github.com/openid/php-openid.git
mv php-openid/Auth/ Auth
rm -r php-openid

---

with repo.php?

May be change «require» paths?

**Comment by vitalif** [comment]
php-openid can be easily installed with PEAR (pear install Auth_OpenID) or system package manager (apt-get install php-openid), so I think it's not needed to include its copy along with the extension...

repo.php can't move folders at the moment.

**Comment by vitalif** [comment]
I've bundled it into the extension repository itself.
